# This file is needed for us to customize what devshop does.
#
# It can be removed once devshop supports yaml-tasks natively.

deploy: |
# @TODO: Change this to a yaml-tasks call with a filter for "va/deploy", once global yaml tests
#  composer yaml-tasks --tests-file=deploy.yml --ansi

test: |
  bin/yaml-tasks --ansi --ignore-ssl --tasks-file=tasks.yml
