name: Apply Labels, owners and reviewers to pull request.

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited]

  schedule:
    - cron: '*/10 * * * *'

jobs:
  pr-team-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.token }}"
      - uses: harupy/auto-labeling@master
        with:
          token: "${{ secrets.token }}"
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'

  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers based upon the author
        uses: necojackarc/auto-request-review@v0.3.0
        with:
          config: ".github/workflows/config/request-review-for-team.yml"
          token: "${{ secrets.token }}"
